# Adam Fitzpatrick
# client.py

# Creates a simple client socket and retrieves data via a GET Request.

# All Code was generated by me with the help of the Class modules and,
# our class book "Networking A Top-Down Approach" chapter 2.7 by James F.
# Kurosh & Keith W. Ross


from socket import *

serverName = "gaia.cs.umass.edu"
serverPort = 80


clientSocket = socket(
    AF_INET, SOCK_STREAM
)  # Creates a TCP socket for reliable delivery and ordered data
clientSocket.connect((serverName, serverPort))

request = ("GET /wireshark-labs/INTRO-wireshark-file1.html "
           "HTTP/1.1\r\nHost:gaia.cs.umass.edu\r\n\r\n")

clientSocket.send(request.encode())  # Sends the encoded GET request
contentReceived = clientSocket.recv(1024)  # Reads up to 1024 bytes of data.

# Prints socket details and the decoded data received from the server.
print(f"\nRequest: {request}")
print(f"Length-Recieved: {len(contentReceived)}")
print(contentReceived.decode())


clientSocket.close()
