# Adam Fitzpatrick
# client_large.py

# Creates a simple client socket and retrieves data via a GET Request. This socket,
# can handle larger amounts of data with the use a loop to display data until the
# server closes the transmission (when bytes read = 0).

# All Code was generated by me with the help of the Class modules and,
# our class book "Networking A Top-Down Approach" chapter 2.7 by James F. Kurose & Keith W. Ross


from socket import *
serverName = 'gaia.cs.umass.edu'
serverPort = 80


clientSocket = socket(AF_INET, SOCK_STREAM)                 # Creates a TCP socket for reliable delivery and ordered data
clientSocket.connect((serverName, serverPort))

request = "GET /wireshark-labs/HTTP-wireshark-file3.html HTTP/1.1\r\nHost:gaia.cs.umass.edu\r\n\r\n"

clientSocket.send(request.encode())                         # Sends the GET request.

print(f"\nRequest: {request}")                              # Print Socket information.


# Loop to read and display 4096 bytes of data at a time, until the server closes the connection. (Bytes read = 0)
while True:
    contentReceived = clientSocket.recv(4096)

    if len(contentReceived) == 0:
        break

    print(f"Length-Recieved: {len(contentReceived)}")
    print(contentReceived.decode())

clientSocket.close()